name: onsunday_forum
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bloc: ^8.1.2
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter_animate: ^4.3.0
  flutter_bloc: ^8.1.3
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
